### ISSUE TITLE
Getting Error while python deployment

### ISSUE THREAD

**Issue by Neetesh1** [dialogflow/fulfillment-weather-nodejs#2]
I tried so many times to deploy python part 3 code on Heroku. but getting 500 internal server error.
Could you please help me or provide me a link where it is deployed

Thanks

**Comment by kishordesai68** [comment]
I am also getting same error

**Comment by sarahdwyer** [comment]
@Neetesh1 @kishordesai68 Can you post your question and specifics in the Python sample repo found here: https://github.com/dialogflow/fulfillment-weather-python?
