### ISSUE TITLE
Cant make http request with intent

### ISSUE THREAD

**Issue by Sidelaunch** [dialogflow/fulfillment-weather-nodejs#4]
So I'm currently trying to have an intent trigger an http request but keep getting errors.

When the intent triggers this code is executed

 const https = require('https');
 https.get('*************', 
  (resp) => {
    let data = '';

    resp.on('data', (chunk) => {
    data += chunk;
    });

    resp.on('end', () => {
    console.log(JSON.parse(data).explanation);
    });

  }).on("error", (err) => {
    console.log("Error: " + err.message);
  });
When running the intent I get Error: getaddrinfo ENOTFOUND back

My code works fine when I run it locally so the issue appears to be something not lining up properly with dialogflow

If anyone has any advice I would greatly appreciate it.

Thanks!

**Comment by WhySongtao** [comment]
Try to upgrade your payment plan to Blaze plan. I was facing the same problem and this fixed it.

**Comment by sarahdwyer** [comment]
@Sidelaunch @WhySongtao 

Dialogflow Fulfillments are hosted as Firebase Cloud Functions. The Firebase free plan only allows Google service API, so if you want to use an external API, you will need to upgrade. There's more information on this [here](https://firebase.google.com/pricing/). There are some restrictions on the Spark plan. If you upgrade to Blaze which does require billing but with use low usage levels there's no charge.
